export const URL =
	"https://corsproxy.io/?https://www.swiggy.com/dapi/restaurants/list/v5?lat=21.1702401&lng=72.83106070000001&page_type=DESKTOP_WEB_LISTING";
export const cloudinarImgUrl =
	"https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_508,h_320,c_fill/";

export const cards = [
	{
		type: "restaurant",
		data: {
			type: "F",
			id: "40161",
			name: "Swaraj (Hotel Three Star Pvt Ltd)",
			uuid: "7461342e-8569-40f1-83b0-eaeb0d906d62",
			city: "5",
			area: "Kharghar",
			totalRatingsString: "5000+ ratings",
			cloudinaryImageId: "okxwnv9yaq6giwleublo",
			cuisines: [
				"Indian",
				"Chinese",
				"Fast Food",
				"South Indian",
				"Beverages",
				"Desserts",
				"Biryani",
			],
			tags: [],
			costForTwo: 29900,
			costForTwoString: "₹299 FOR TWO",
			deliveryTime: 42,
			minDeliveryTime: 42,
			maxDeliveryTime: 42,
			slaString: "42 MINS",
			lastMileTravel: 8.600000381469727,
			slugs: {
				restaurant: "swaraj-kharghar-kharghar",
				city: "mumbai",
			},
			cityState: "5",
			address: "18/27, Crystal Plaza, Sector 7, Kharghar, Navi Mumbai",
			locality: "Sector 7",
			parentId: 199026,
			unserviceable: false,
			veg: false,
			select: false,
			favorite: false,
			tradeCampaignHeaders: [],
			ribbon: [
				{
					type: "PROMOTED",
				},
			],
			chain: [],
			feeDetails: {
				fees: [
					{
						name: "distance",
						fee: 7400,
						message: "",
					},
					{
						name: "time",
						fee: 0,
						message: "",
					},
					{
						name: "special",
						fee: 0,
						message: "",
					},
				],
				totalFees: 7400,
				message: "",
				title: "Delivery Charge",
				amount: "7400",
				icon: "",
			},
			availability: {
				opened: true,
				nextOpenMessage: "",
				nextCloseMessage: "",
			},
			longDistanceEnabled: 0,
			rainMode: "NONE",
			thirdPartyAddress: false,
			thirdPartyVendor: "",
			adTrackingID:
				"cid=7314820~p=1~eid=00000189-2ed2-f07c-01cb-f6fc00480133~srvts=1688707723388",
			badges: {
				imageBased: [],
				textBased: [],
				textExtendedBadges: [],
			},
			lastMileTravelString: "8.6 kms",
			hasSurge: false,
			aggregatedDiscountInfoV3: {
				header: "₹100 OFF",
				subHeader: "ABOVE ₹199",
				discountTag: "FLAT DEAL",
				headerTypeV2: 0,
			},
			loyaltyDiscoverPresentationInfo: {
				logoCtx: {
					text: "BENEFITS",
					logo: "v1634558776/swiggy_one/OneLogo_3x.png",
				},
				freedelMessage: "FREE DELIVERY",
				exclusiveOfferMessage: "",
			},
			sla: {
				restaurantId: "40161",
				deliveryTime: 42,
				minDeliveryTime: 42,
				maxDeliveryTime: 42,
				lastMileTravel: 8.600000381469727,
				lastMileDistance: 0,
				serviceability: "SERVICEABLE",
				rainMode: "NONE",
				longDistance: "NOT_LONG_DISTANCE",
				preferentialService: false,
				iconType: "EMPTY",
			},
			promoted: true,
			avgRating: "4.2",
			totalRatings: 5000,
			new: false,
		},
		subtype: "basic",
	},
	{
		type: "restaurant",
		data: {
			type: "F",
			id: "554326",
			name: "Banglore Iyenger Bakery",
			uuid: "40c23c79-3ac8-49be-8d74-67e893568d09",
			city: "5",
			area: "Nerul",
			totalRatingsString: "50+ ratings",
			cloudinaryImageId: "cvbrr65pttv94qrkem5e",
			cuisines: ["Bakery", "Snacks"],
			tags: [],
			costForTwo: 20000,
			costForTwoString: "₹200 FOR TWO",
			deliveryTime: 22,
			minDeliveryTime: 22,
			maxDeliveryTime: 22,
			slaString: "22 MINS",
			lastMileTravel: 0.20000000298023224,
			slugs: {
				restaurant: "banglore-iyenger-bakery-nerul-nerul",
				city: "mumbai",
			},
			cityState: "5",
			address:
				"SHOPNO6PLOTNO268SWASTIKSINDHUCO OP HSGSOCIETYJUINAGARSECTOR23SANPADANAVIMUMBAI- 400705, Navi Mumbai Municipal CorporationThanZone3Maharashtra400705&quo",
			locality: "Sector-23",
			parentId: 41406,
			unserviceable: false,
			veg: false,
			select: false,
			favorite: false,
			tradeCampaignHeaders: [],
			chain: [],
			feeDetails: {
				fees: [
					{
						name: "distance",
						fee: 2900,
						message: "",
					},
					{
						name: "time",
						fee: 0,
						message: "",
					},
					{
						name: "special",
						fee: 0,
						message: "",
					},
				],
				totalFees: 2900,
				message: "",
				title: "Delivery Charge",
				amount: "2900",
				icon: "",
			},
			availability: {
				opened: true,
				nextOpenMessage: "",
				nextCloseMessage: "",
			},
			longDistanceEnabled: 0,
			rainMode: "NONE",
			thirdPartyAddress: false,
			thirdPartyVendor: "",
			adTrackingID: "",
			badges: {
				imageBased: [],
				textBased: [],
				textExtendedBadges: [],
			},
			lastMileTravelString: "0.2 kms",
			hasSurge: false,
			loyaltyDiscoverPresentationInfo: {
				logoCtx: {
					text: "BENEFITS",
					logo: "v1634558776/swiggy_one/OneLogo_3x.png",
				},
				freedelMessage: "FREE DELIVERY",
				exclusiveOfferMessage: "",
			},
			sla: {
				restaurantId: "554326",
				deliveryTime: 22,
				minDeliveryTime: 22,
				maxDeliveryTime: 22,
				lastMileTravel: 0.20000000298023224,
				lastMileDistance: 0,
				serviceability: "SERVICEABLE",
				rainMode: "NONE",
				longDistance: "NOT_LONG_DISTANCE",
				preferentialService: false,
				iconType: "EMPTY",
			},
			promoted: false,
			avgRating: "4.4",
			totalRatings: 50,
			new: false,
		},
		subtype: "basic",
	},
	{
		type: "restaurant",
		data: {
			type: "F",
			id: "413345",
			name: "Mahesh Mishthan",
			uuid: "d21dc1f8-373f-4f8e-9f1f-10b46e425a27",
			city: "5",
			area: "Nerul",
			totalRatingsString: "100+ ratings",
			cloudinaryImageId: "ojic5dukauq2iivr0506",
			cuisines: ["Sweets", "Snacks"],
			tags: [],
			costForTwo: 25000,
			costForTwoString: "₹250 FOR TWO",
			deliveryTime: 44,
			minDeliveryTime: 44,
			maxDeliveryTime: 44,
			slaString: "44 MINS",
			lastMileTravel: 0.4000000059604645,
			slugs: {
				restaurant: "mahesh-mishthan-nerul-nerul",
				city: "mumbai",
			},
			cityState: "5",
			address:
				"SHOP NO 7, PLOT NO. 262, SECTOR 23, VONAY CO.OP.HSG. SOC, JUINAGAR, NAVI MUMBAI, NERUL ZONE (EAST), NAVI MUMBAI MUNICIPAL CORPORATION (THANE ZONE-4) MAHARASHTRA",
			locality: "Sector 23",
			parentId: 249995,
			unserviceable: false,
			veg: false,
			select: false,
			favorite: false,
			tradeCampaignHeaders: [],
			chain: [],
			feeDetails: {
				fees: [
					{
						name: "distance",
						fee: 2900,
						message: "",
					},
					{
						name: "time",
						fee: 0,
						message: "",
					},
					{
						name: "special",
						fee: 0,
						message: "",
					},
				],
				totalFees: 2900,
				message: "",
				title: "Delivery Charge",
				amount: "2900",
				icon: "",
			},
			availability: {
				opened: true,
				nextOpenMessage: "",
				nextCloseMessage: "",
			},
			longDistanceEnabled: 0,
			rainMode: "NONE",
			thirdPartyAddress: false,
			thirdPartyVendor: "",
			adTrackingID: "",
			badges: {
				imageBased: [],
				textBased: [],
				textExtendedBadges: [],
			},
			lastMileTravelString: "0.4 kms",
			hasSurge: false,
			loyaltyDiscoverPresentationInfo: {
				logoCtx: {
					text: "BENEFITS",
					logo: "v1634558776/swiggy_one/OneLogo_3x.png",
				},
				freedelMessage: "FREE DELIVERY",
				exclusiveOfferMessage: "",
			},
			sla: {
				restaurantId: "413345",
				deliveryTime: 44,
				minDeliveryTime: 44,
				maxDeliveryTime: 44,
				lastMileTravel: 0.4000000059604645,
				lastMileDistance: 0,
				serviceability: "SERVICEABLE",
				rainMode: "NONE",
				longDistance: "NOT_LONG_DISTANCE",
				preferentialService: false,
				iconType: "EMPTY",
			},
			promoted: false,
			avgRating: "4.0",
			totalRatings: 100,
			new: false,
		},
		subtype: "basic",
	},
	{
		type: "restaurant",
		data: {
			type: "F",
			id: "695602",
			name: "Brijwasi Sweets, Original Since 1946",
			uuid: "97c46c1c-4a70-4bfc-b896-44a7df2e0395",
			city: "5",
			area: "Vashi",
			totalRatingsString: "Too Few Ratings",
			cloudinaryImageId: "ef538e88c5e150ce4cbfca107b9e758c",
			cuisines: ["Indian", "Sweets", "Desserts"],
			tags: [],
			costForTwo: 40000,
			costForTwoString: "₹400 FOR TWO",
			deliveryTime: 27,
			minDeliveryTime: 27,
			maxDeliveryTime: 27,
			slaString: "27 MINS",
			lastMileTravel: 4.5,
			slugs: {
				restaurant:
					"brijwasi-sweets,-original-since-1946-chembur-chembur-2",
				city: "mumbai",
			},
			cityState: "5",
			address:
				"Grain Merchants Society, Shop No. 17, Ground Floor, Vashi, Sector 17, Navi Mumbai",
			locality: "Station Road",
			parentId: 409024,
			unserviceable: false,
			veg: false,
			select: false,
			favorite: false,
			tradeCampaignHeaders: [],
			ribbon: [
				{
					type: "PROMOTED",
				},
			],
			chain: [],
			feeDetails: {
				fees: [
					{
						name: "distance",
						fee: 4100,
						message: "",
					},
					{
						name: "time",
						fee: 0,
						message: "",
					},
					{
						name: "special",
						fee: 0,
						message: "",
					},
				],
				totalFees: 4100,
				message: "",
				title: "Delivery Charge",
				amount: "4100",
				icon: "",
			},
			availability: {
				opened: true,
				nextOpenMessage: "",
				nextCloseMessage: "",
			},
			longDistanceEnabled: 0,
			rainMode: "NONE",
			thirdPartyAddress: false,
			thirdPartyVendor: "",
			adTrackingID:
				"cid=7384940~p=4~eid=00000189-2ed2-f07c-01cb-f6fd0048045c~srvts=1688707723388",
			badges: {
				imageBased: [],
				textBased: [],
				textExtendedBadges: [],
			},
			lastMileTravelString: "4.5 kms",
			hasSurge: false,
			aggregatedDiscountInfoV3: {
				header: "20% OFF",
				subHeader: "UPTO ₹50",
				discountTag: "",
				headerTypeV2: 0,
			},
			loyaltyDiscoverPresentationInfo: {
				logoCtx: {
					text: "BENEFITS",
					logo: "v1634558776/swiggy_one/OneLogo_3x.png",
				},
				freedelMessage: "FREE DELIVERY",
				exclusiveOfferMessage: "",
			},
			sla: {
				restaurantId: "695602",
				deliveryTime: 27,
				minDeliveryTime: 27,
				maxDeliveryTime: 27,
				lastMileTravel: 4.5,
				lastMileDistance: 0,
				serviceability: "SERVICEABLE",
				rainMode: "NONE",
				longDistance: "NOT_LONG_DISTANCE",
				preferentialService: false,
				iconType: "EMPTY",
			},
			promoted: true,
			avgRating: "--",
			totalRatings: 0,
			new: false,
		},
		subtype: "basic",
	},
	{
		type: "restaurant",
		data: {
			type: "F",
			id: "570955",
			name: "Jumboking Indian Burger",
			uuid: "6a0b26cd-e214-4e3d-84ad-f31c05c6c2d9",
			city: "5",
			area: "Juhinagar",
			totalRatingsString: "20+ ratings",
			cloudinaryImageId: "f7d08c14959643da32f92f634c1f2ff0",
			cuisines: ["American", "Fast Food", "Beverages"],
			tags: [],
			costForTwo: 15000,
			costForTwoString: "₹150 FOR TWO",
			deliveryTime: 23,
			minDeliveryTime: 23,
			maxDeliveryTime: 23,
			slaString: "23 MINS",
			lastMileTravel: 0.699999988079071,
			slugs: {
				restaurant: "jumboking-indian-burger-vashi-vashi-2",
				city: "mumbai",
			},
			cityState: "5",
			address:
				"SHOP NO. E -002, GROUND FLOOR, RAILWAY STATION COMPLEX, JUINAGAR, Navi Mumbai-400706",
			locality: "Vashi",
			parentId: 515,
			unserviceable: false,
			veg: true,
			select: false,
			favorite: false,
			tradeCampaignHeaders: [],
			chain: [],
			feeDetails: {
				fees: [
					{
						name: "distance",
						fee: 2900,
						message: "",
					},
					{
						name: "time",
						fee: 0,
						message: "",
					},
					{
						name: "special",
						fee: 0,
						message: "",
					},
				],
				totalFees: 2900,
				message: "",
				title: "Delivery Charge",
				amount: "2900",
				icon: "",
			},
			availability: {
				opened: true,
				nextOpenMessage: "",
				nextCloseMessage: "",
			},
			longDistanceEnabled: 0,
			rainMode: "NONE",
			thirdPartyAddress: false,
			thirdPartyVendor: "",
			adTrackingID: "",
			badges: {
				imageBased: [],
				textBased: [],
				textExtendedBadges: [],
			},
			lastMileTravelString: "0.6 kms",
			hasSurge: false,
			aggregatedDiscountInfoV3: {
				header: "20% OFF",
				subHeader: "UPTO ₹50",
				discountTag: "",
				headerTypeV2: 0,
			},
			loyaltyDiscoverPresentationInfo: {
				logoCtx: {
					text: "BENEFITS",
					logo: "v1634558776/swiggy_one/OneLogo_3x.png",
				},
				freedelMessage: "FREE DELIVERY",
				exclusiveOfferMessage: "",
			},
			sla: {
				restaurantId: "570955",
				deliveryTime: 23,
				minDeliveryTime: 23,
				maxDeliveryTime: 23,
				lastMileTravel: 0.699999988079071,
				lastMileDistance: 0,
				serviceability: "SERVICEABLE",
				rainMode: "NONE",
				longDistance: "NOT_LONG_DISTANCE",
				preferentialService: false,
				iconType: "EMPTY",
			},
			promoted: false,
			avgRating: "4.0",
			totalRatings: 20,
			new: false,
		},
		subtype: "basic",
	},
	{
		type: "restaurant",
		data: {
			type: "F",
			id: "262716",
			name: "Dadi Ka Khazana",
			uuid: "3c6e1ae3-214e-4b1b-8f37-01b22882550a",
			city: "5",
			area: "Nerul",
			totalRatingsString: "1000+ ratings",
			cloudinaryImageId: "jjjwah3zujfjubocb2qm",
			cuisines: ["Indian", "Thalis", "North Indian"],
			tags: [],
			costForTwo: 20000,
			costForTwoString: "₹200 FOR TWO",
			deliveryTime: 34,
			minDeliveryTime: 34,
			maxDeliveryTime: 34,
			slaString: "34 MINS",
			lastMileTravel: 0.8999999761581421,
			slugs: {
				restaurant: "dadi-ka-khazana-vashi-vashi-2",
				city: "mumbai",
			},
			cityState: "5",
			address:
				"SHOP NO -11, PHASE-II, SECTOR-02, NERUL,NAVI MUMVAI, Nerul Zone (West), Navi Mumbai Municipal Corporation (Thane Zone-4), Maharashtra-400706",
			locality: "Vashi",
			parentId: 6958,
			unserviceable: false,
			veg: true,
			select: false,
			favorite: false,
			tradeCampaignHeaders: [],
			chain: [],
			feeDetails: {
				fees: [
					{
						name: "distance",
						fee: 2900,
						message: "",
					},
					{
						name: "time",
						fee: 0,
						message: "",
					},
					{
						name: "special",
						fee: 0,
						message: "",
					},
				],
				totalFees: 2900,
				message: "",
				title: "Delivery Charge",
				amount: "2900",
				icon: "",
			},
			availability: {
				opened: true,
				nextOpenMessage: "",
				nextCloseMessage: "",
			},
			longDistanceEnabled: 0,
			rainMode: "NONE",
			thirdPartyAddress: false,
			thirdPartyVendor: "",
			adTrackingID: "",
			badges: {
				imageBased: [],
				textBased: [],
				textExtendedBadges: [],
			},
			lastMileTravelString: "0.8 kms",
			hasSurge: false,
			aggregatedDiscountInfoV3: {
				header: "25% OFF",
				subHeader: "UPTO ₹65",
				discountTag: "",
				headerTypeV2: 0,
			},
			loyaltyDiscoverPresentationInfo: {
				logoCtx: {
					text: "BENEFITS",
					logo: "v1634558776/swiggy_one/OneLogo_3x.png",
				},
				freedelMessage: "FREE DELIVERY",
				exclusiveOfferMessage: "",
			},
			sla: {
				restaurantId: "262716",
				deliveryTime: 34,
				minDeliveryTime: 34,
				maxDeliveryTime: 34,
				lastMileTravel: 0.8999999761581421,
				lastMileDistance: 0,
				serviceability: "SERVICEABLE",
				rainMode: "NONE",
				longDistance: "NOT_LONG_DISTANCE",
				preferentialService: false,
				iconType: "EMPTY",
			},
			promoted: false,
			avgRating: "3.9",
			totalRatings: 1000,
			new: false,
		},
		subtype: "basic",
	},
	{
		type: "restaurant",
		data: {
			type: "F",
			id: "318311",
			name: "Bhuvika Bhavan",
			uuid: "ed17f770-cda7-4166-8fd7-cbc0880b30bb",
			city: "5",
			area: "Kharghar",
			totalRatingsString: "1000+ ratings",
			cloudinaryImageId: "tmrdopkuumfxftbk3znu",
			cuisines: ["South Indian", "North Indian"],
			tags: [],
			costForTwo: 20000,
			costForTwoString: "₹200 FOR TWO",
			deliveryTime: 37,
			minDeliveryTime: 37,
			maxDeliveryTime: 37,
			slaString: "37 MINS",
			lastMileTravel: 8.600000381469727,
			slugs: {
				restaurant: "bhuvika-bhavan-kharghar-kharghar",
				city: "mumbai",
			},
			cityState: "5",
			address:
				"Shop 57, Crystal Plaza, Hiranandani, Sector 7, Kharghar, Navi Mumbai",
			locality: "Crystal Plaza",
			parentId: 45389,
			unserviceable: false,
			veg: false,
			select: false,
			favorite: false,
			tradeCampaignHeaders: [],
			ribbon: [
				{
					type: "PROMOTED",
				},
			],
			chain: [],
			feeDetails: {
				fees: [
					{
						name: "distance",
						fee: 7400,
						message: "",
					},
					{
						name: "time",
						fee: 0,
						message: "",
					},
					{
						name: "special",
						fee: 0,
						message: "",
					},
				],
				totalFees: 7400,
				message: "",
				title: "Delivery Charge",
				amount: "7400",
				icon: "",
			},
			availability: {
				opened: true,
				nextOpenMessage: "",
				nextCloseMessage: "",
			},
			longDistanceEnabled: 0,
			rainMode: "NONE",
			thirdPartyAddress: false,
			thirdPartyVendor: "",
			adTrackingID:
				"cid=7260287~p=7~eid=00000189-2ed2-f07c-01cb-f6fe0048070e~srvts=1688707723388",
			badges: {
				imageBased: [],
				textBased: [],
				textExtendedBadges: [],
			},
			lastMileTravelString: "8.6 kms",
			hasSurge: false,
			aggregatedDiscountInfoV3: {
				header: "20% OFF",
				subHeader: "UPTO ₹50",
				discountTag: "",
				headerTypeV2: 0,
			},
			loyaltyDiscoverPresentationInfo: {
				logoCtx: {
					text: "BENEFITS",
					logo: "v1634558776/swiggy_one/OneLogo_3x.png",
				},
				freedelMessage: "FREE DELIVERY",
				exclusiveOfferMessage: "",
			},
			sla: {
				restaurantId: "318311",
				deliveryTime: 37,
				minDeliveryTime: 37,
				maxDeliveryTime: 37,
				lastMileTravel: 8.600000381469727,
				lastMileDistance: 0,
				serviceability: "SERVICEABLE",
				rainMode: "NONE",
				longDistance: "NOT_LONG_DISTANCE",
				preferentialService: false,
				iconType: "EMPTY",
			},
			promoted: true,
			avgRating: "4.3",
			totalRatings: 1000,
			new: false,
		},
		subtype: "basic",
	},
	{
		type: "restaurant",
		data: {
			type: "F",
			id: "393760",
			name: "ZippyFeed",
			uuid: "282c5c96-eff4-4cfc-a9fe-f6b94c0934f2",
			city: "5",
			area: "Nerul",
			totalRatingsString: "50+ ratings",
			cloudinaryImageId: "sbnkbqzmfgikvf9auphz",
			cuisines: ["Fast Food", "Biryani", "Pizzas"],
			tags: [],
			costForTwo: 20000,
			costForTwoString: "₹200 FOR TWO",
			deliveryTime: 34,
			minDeliveryTime: 34,
			maxDeliveryTime: 34,
			slaString: "34 MINS",
			lastMileTravel: 0.30000001192092896,
			slugs: {
				restaurant: "zippyfeed-nerul-nerul",
				city: "mumbai",
			},
			cityState: "5",
			address:
				"SSHOP NO 006,PLOT NO199/202, OM SAI CHAYA CHS , SECTOR 23,GES, JUINAGAR ,400706",
			locality: "Nerul",
			parentId: 230044,
			unserviceable: false,
			veg: false,
			select: false,
			favorite: false,
			tradeCampaignHeaders: [],
			chain: [],
			feeDetails: {
				fees: [
					{
						name: "distance",
						fee: 2900,
						message: "",
					},
					{
						name: "time",
						fee: 0,
						message: "",
					},
					{
						name: "special",
						fee: 0,
						message: "",
					},
				],
				totalFees: 2900,
				message: "",
				title: "Delivery Charge",
				amount: "2900",
				icon: "",
			},
			availability: {
				opened: true,
				nextOpenMessage: "",
				nextCloseMessage: "",
			},
			longDistanceEnabled: 0,
			rainMode: "NONE",
			thirdPartyAddress: false,
			thirdPartyVendor: "",
			adTrackingID: "",
			badges: {
				imageBased: [],
				textBased: [],
				textExtendedBadges: [],
			},
			lastMileTravelString: "0.3 kms",
			hasSurge: false,
			loyaltyDiscoverPresentationInfo: {
				logoCtx: {
					text: "BENEFITS",
					logo: "v1634558776/swiggy_one/OneLogo_3x.png",
				},
				freedelMessage: "FREE DELIVERY",
				exclusiveOfferMessage: "",
			},
			sla: {
				restaurantId: "393760",
				deliveryTime: 34,
				minDeliveryTime: 34,
				maxDeliveryTime: 34,
				lastMileTravel: 0.30000001192092896,
				lastMileDistance: 0,
				serviceability: "SERVICEABLE",
				rainMode: "NONE",
				longDistance: "NOT_LONG_DISTANCE",
				preferentialService: false,
				iconType: "EMPTY",
			},
			promoted: false,
			avgRating: "3.4",
			totalRatings: 50,
			new: false,
		},
		subtype: "basic",
	},
	{
		type: "restaurant",
		data: {
			type: "F",
			id: "714713",
			name: "Aroma Chai - & Snacks Cafe",
			uuid: "74e9a240-9356-460a-931c-fa503935875c",
			city: "5",
			area: "Juinagar",
			totalRatingsString: "Too Few Ratings",
			cloudinaryImageId: "39ea460fc8a02af44bc5a97d4594c7f1",
			cuisines: ["Beverages", "Snacks"],
			tags: [],
			costForTwo: 20000,
			costForTwoString: "₹200 FOR TWO",
			deliveryTime: 32,
			minDeliveryTime: 32,
			maxDeliveryTime: 32,
			slaString: "32 MINS",
			lastMileTravel: 0.4000000059604645,
			slugs: {
				restaurant: "aroma-chai---&-snacks-cafe-nerul-nerul-3",
				city: "mumbai",
			},
			cityState: "5",
			address:
				"Shop No 5, Plot No 265, Aroma Chai, Shree Ganesh Apartment, Sector 23, Juinagar, Navi Mumbai, Maharashtra 400705, India",
			locality: "Aroma Chai",
			parentId: 422100,
			unserviceable: false,
			veg: true,
			select: false,
			favorite: false,
			tradeCampaignHeaders: [],
			chain: [],
			feeDetails: {
				fees: [
					{
						name: "distance",
						fee: 2900,
						message: "",
					},
					{
						name: "time",
						fee: 0,
						message: "",
					},
					{
						name: "special",
						fee: 0,
						message: "",
					},
				],
				totalFees: 2900,
				message: "",
				title: "Delivery Charge",
				amount: "2900",
				icon: "",
			},
			availability: {
				opened: true,
				nextOpenMessage: "",
				nextCloseMessage: "",
			},
			longDistanceEnabled: 0,
			rainMode: "NONE",
			thirdPartyAddress: false,
			thirdPartyVendor: "",
			adTrackingID: "",
			badges: {
				imageBased: [],
				textBased: [],
				textExtendedBadges: [],
			},
			lastMileTravelString: "0.4 kms",
			hasSurge: false,
			aggregatedDiscountInfoV3: {
				header: "40% OFF",
				subHeader: "UPTO ₹80",
				discountTag: "",
				headerTypeV2: 0,
			},
			loyaltyDiscoverPresentationInfo: {
				logoCtx: {
					text: "BENEFITS",
					logo: "v1634558776/swiggy_one/OneLogo_3x.png",
				},
				freedelMessage: "FREE DELIVERY",
				exclusiveOfferMessage: "",
			},
			sla: {
				restaurantId: "714713",
				deliveryTime: 32,
				minDeliveryTime: 32,
				maxDeliveryTime: 32,
				lastMileTravel: 0.4000000059604645,
				lastMileDistance: 0,
				serviceability: "SERVICEABLE",
				rainMode: "NONE",
				longDistance: "NOT_LONG_DISTANCE",
				preferentialService: false,
				iconType: "EMPTY",
			},
			promoted: false,
			avgRating: "--",
			totalRatings: 0,
			new: true,
		},
		subtype: "basic",
	},
	{
		type: "restaurant",
		data: {
			type: "F",
			id: "144577",
			name: "Frostalicious Cake",
			uuid: "e7393df5-c688-43d2-9036-2370dc71cc4d",
			city: "5",
			area: "Turbhe",
			totalRatingsString: "1000+ ratings",
			cloudinaryImageId: "pkyyrka4xgikoqtdn0rv",
			cuisines: ["Bakery", "Desserts"],
			tags: [],
			costForTwo: 40000,
			costForTwoString: "₹400 FOR TWO",
			deliveryTime: 42,
			minDeliveryTime: 42,
			maxDeliveryTime: 42,
			slaString: "42 MINS",
			lastMileTravel: 3,
			slugs: {
				restaurant: "frostalicious-cake-vashi-vashi",
				city: "mumbai",
			},
			cityState: "5",
			address:
				"Frostalicious Cake, Near Hanuman Mandir, Sector 22, Turbhe Village, Navi Mumbai",
			locality: "Vashi",
			parentId: 7198,
			unserviceable: false,
			veg: true,
			select: false,
			favorite: false,
			tradeCampaignHeaders: [],
			ribbon: [
				{
					type: "PROMOTED",
				},
			],
			chain: [],
			feeDetails: {
				fees: [
					{
						name: "distance",
						fee: 3500,
						message: "",
					},
					{
						name: "time",
						fee: 0,
						message: "",
					},
					{
						name: "special",
						fee: 0,
						message: "",
					},
				],
				totalFees: 3500,
				message: "",
				title: "Delivery Charge",
				amount: "3500",
				icon: "",
			},
			availability: {
				opened: true,
				nextOpenMessage: "",
				nextCloseMessage: "",
			},
			longDistanceEnabled: 0,
			rainMode: "NONE",
			thirdPartyAddress: false,
			thirdPartyVendor: "",
			adTrackingID:
				"cid=7314808~p=10~eid=00000189-2ed2-f07c-01cb-f6ff00480a0a~srvts=1688707723388",
			badges: {
				imageBased: [],
				textBased: [],
				textExtendedBadges: [],
			},
			lastMileTravelString: "3 kms",
			hasSurge: false,
			aggregatedDiscountInfoV3: {
				header: "₹125 OFF",
				subHeader: "ABOVE ₹599",
				discountTag: "FLAT DEAL",
				headerTypeV2: 0,
			},
			loyaltyDiscoverPresentationInfo: {
				logoCtx: {
					text: "BENEFITS",
					logo: "v1634558776/swiggy_one/OneLogo_3x.png",
				},
				freedelMessage: "FREE DELIVERY",
				exclusiveOfferMessage: "",
			},
			sla: {
				restaurantId: "144577",
				deliveryTime: 42,
				minDeliveryTime: 42,
				maxDeliveryTime: 42,
				lastMileTravel: 3,
				lastMileDistance: 0,
				serviceability: "SERVICEABLE",
				rainMode: "NONE",
				longDistance: "NOT_LONG_DISTANCE",
				preferentialService: false,
				iconType: "EMPTY",
			},
			promoted: true,
			avgRating: "4.1",
			totalRatings: 1000,
			new: false,
		},
		subtype: "basic",
	},
	{
		type: "restaurant",
		data: {
			type: "F",
			id: "216853",
			name: "Social Beans Cafe",
			uuid: "b40d256a-4c79-4309-8da7-a6e96a94a7ad",
			city: "5",
			area: "Sanpada",
			totalRatingsString: "100+ ratings",
			cloudinaryImageId: "yhbkqpsrixcscnt4wpkb",
			cuisines: ["Italian"],
			tags: [],
			costForTwo: 30000,
			costForTwoString: "₹300 FOR TWO",
			deliveryTime: 29,
			minDeliveryTime: 29,
			maxDeliveryTime: 29,
			slaString: "29 MINS",
			lastMileTravel: 0.6000000238418579,
			slugs: {
				restaurant: "social-bean-vashi-vashi",
				city: "mumbai",
			},
			cityState: "5",
			address:
				"Vasundhara Heights, Sector 11, Sanpada, Navi Mumbai, Maharashtra, India",
			locality: "Sector 11",
			parentId: 190579,
			unserviceable: false,
			veg: false,
			select: false,
			favorite: false,
			tradeCampaignHeaders: [],
			chain: [],
			feeDetails: {
				fees: [
					{
						name: "distance",
						fee: 2900,
						message: "",
					},
					{
						name: "time",
						fee: 0,
						message: "",
					},
					{
						name: "special",
						fee: 0,
						message: "",
					},
				],
				totalFees: 2900,
				message: "",
				title: "Delivery Charge",
				amount: "2900",
				icon: "",
			},
			availability: {
				opened: true,
				nextOpenMessage: "",
				nextCloseMessage: "",
			},
			longDistanceEnabled: 0,
			rainMode: "NONE",
			thirdPartyAddress: false,
			thirdPartyVendor: "",
			adTrackingID: "",
			badges: {
				imageBased: [],
				textBased: [],
				textExtendedBadges: [],
			},
			lastMileTravelString: "0.6 kms",
			hasSurge: false,
			loyaltyDiscoverPresentationInfo: {
				logoCtx: {
					text: "BENEFITS",
					logo: "v1634558776/swiggy_one/OneLogo_3x.png",
				},
				freedelMessage: "FREE DELIVERY",
				exclusiveOfferMessage: "",
			},
			sla: {
				restaurantId: "216853",
				deliveryTime: 29,
				minDeliveryTime: 29,
				maxDeliveryTime: 29,
				lastMileTravel: 0.6000000238418579,
				lastMileDistance: 0,
				serviceability: "SERVICEABLE",
				rainMode: "NONE",
				longDistance: "NOT_LONG_DISTANCE",
				preferentialService: false,
				iconType: "EMPTY",
			},
			promoted: false,
			avgRating: "4.3",
			totalRatings: 100,
			new: false,
		},
		subtype: "basic",
	},
	{
		type: "restaurant",
		data: {
			type: "F",
			id: "42580",
			name: "Burger King",
			uuid: "dfcc61be-457d-4e29-b153-4ef8bbc9c69b",
			city: "5",
			area: "Nerul",
			totalRatingsString: "10000+ ratings",
			cloudinaryImageId: "e33e1d3ba7d6b2bb0d45e1001b731fcf",
			cuisines: ["Burgers", "American"],
			tags: [],
			costForTwo: 35000,
			costForTwoString: "₹350 FOR TWO",
			deliveryTime: 28,
			minDeliveryTime: 28,
			maxDeliveryTime: 28,
			slaString: "28 MINS",
			lastMileTravel: 2,
			slugs: {
				restaurant: "burger-king-ag-patil-marg-nerul-nerul",
				city: "mumbai",
			},
			cityState: "5",
			address:
				"Plot no 5, sector 1, AG Patil Marg, Nerul, Navi Mumbai 410706",
			locality: "AG Patil Marg",
			parentId: 166,
			unserviceable: false,
			veg: false,
			select: false,
			favorite: false,
			tradeCampaignHeaders: [],
			chain: [],
			feeDetails: {
				fees: [
					{
						name: "distance",
						fee: 2900,
						message: "",
					},
					{
						name: "time",
						fee: 0,
						message: "",
					},
					{
						name: "special",
						fee: 0,
						message: "",
					},
				],
				totalFees: 2900,
				message: "",
				title: "Delivery Charge",
				amount: "2900",
				icon: "",
			},
			availability: {
				opened: true,
				nextOpenMessage: "",
				nextCloseMessage: "",
			},
			longDistanceEnabled: 0,
			rainMode: "NONE",
			thirdPartyAddress: false,
			thirdPartyVendor: "",
			adTrackingID: "",
			badges: {
				imageBased: [],
				textBased: [],
				textExtendedBadges: [],
			},
			lastMileTravelString: "2 kms",
			hasSurge: false,
			aggregatedDiscountInfoV3: {
				header: "60% OFF",
				subHeader: "UPTO ₹120",
				discountTag: "",
				headerTypeV2: 0,
			},
			loyaltyDiscoverPresentationInfo: {
				logoCtx: {
					text: "BENEFITS",
					logo: "v1634558776/swiggy_one/OneLogo_3x.png",
				},
				freedelMessage: "FREE DELIVERY",
				exclusiveOfferMessage: "",
			},
			sla: {
				restaurantId: "42580",
				deliveryTime: 28,
				minDeliveryTime: 28,
				maxDeliveryTime: 28,
				lastMileTravel: 2,
				lastMileDistance: 0,
				serviceability: "SERVICEABLE",
				rainMode: "NONE",
				longDistance: "NOT_LONG_DISTANCE",
				preferentialService: false,
				iconType: "EMPTY",
			},
			promoted: false,
			avgRating: "4.2",
			totalRatings: 10000,
			new: false,
		},
		subtype: "basic",
	},
	{
		type: "restaurant",
		data: {
			type: "F",
			id: "103801",
			name: "Starbucks Coffee",
			uuid: "e644c759-a115-4d4f-8d03-c3e923f4f6d5",
			city: "5",
			area: "Nerul",
			totalRatingsString: "1000+ ratings",
			cloudinaryImageId: "4df3497f1460dfd1ecd8125222f6d362",
			cuisines: [
				"Beverages",
				"Cafe",
				"Snacks",
				"Desserts",
				"Bakery",
				"Ice Cream",
			],
			tags: [],
			costForTwo: 40000,
			costForTwoString: "₹400 FOR TWO",
			deliveryTime: 32,
			minDeliveryTime: 32,
			maxDeliveryTime: 32,
			slaString: "32 MINS",
			lastMileTravel: 4.099999904632568,
			slugs: {
				restaurant: "starbucks-coffee-grand-central-mall-nerul",
				city: "mumbai",
			},
			cityState: "5",
			address:
				"Upper Ground Floor, Grand Central Mall,Sector 40, Seaewoods railway station, Mumbai",
			locality: "Grand Central Mall",
			parentId: 195515,
			unserviceable: false,
			veg: false,
			select: false,
			favorite: false,
			tradeCampaignHeaders: [],
			ribbon: [
				{
					type: "PROMOTED",
				},
			],
			chain: [],
			feeDetails: {
				fees: [
					{
						name: "distance",
						fee: 4100,
						message: "",
					},
					{
						name: "time",
						fee: 0,
						message: "",
					},
					{
						name: "special",
						fee: 0,
						message: "",
					},
				],
				totalFees: 4100,
				message: "",
				title: "Delivery Charge",
				amount: "4100",
				icon: "",
			},
			availability: {
				opened: true,
				nextOpenMessage: "",
				nextCloseMessage: "",
			},
			longDistanceEnabled: 0,
			rainMode: "NONE",
			thirdPartyAddress: false,
			thirdPartyVendor: "",
			adTrackingID:
				"cid=7354794~p=13~eid=00000189-2ed2-f07c-01cb-f70000480d22~srvts=1688707723388",
			badges: {
				imageBased: [],
				textBased: [],
				textExtendedBadges: [],
			},
			lastMileTravelString: "4 kms",
			hasSurge: false,
			aggregatedDiscountInfoV3: {
				header: "₹125 OFF",
				subHeader: "ABOVE ₹319",
				discountTag: "FLAT DEAL",
				headerTypeV2: 0,
			},
			loyaltyDiscoverPresentationInfo: {
				logoCtx: {
					text: "BENEFITS",
					logo: "v1634558776/swiggy_one/OneLogo_3x.png",
				},
				freedelMessage: "FREE DELIVERY",
				exclusiveOfferMessage: "",
			},
			sla: {
				restaurantId: "103801",
				deliveryTime: 32,
				minDeliveryTime: 32,
				maxDeliveryTime: 32,
				lastMileTravel: 4.099999904632568,
				lastMileDistance: 0,
				serviceability: "SERVICEABLE",
				rainMode: "NONE",
				longDistance: "NOT_LONG_DISTANCE",
				preferentialService: false,
				iconType: "EMPTY",
			},
			promoted: true,
			avgRating: "4.2",
			totalRatings: 1000,
			new: false,
		},
		subtype: "basic",
	},
	{
		type: "restaurant",
		data: {
			type: "F",
			id: "645850",
			name: "Om Sai Hotel",
			uuid: "ddbdc5aa-1c2b-4975-a153-ece8587b9cf6",
			city: "5",
			area: "Nerul",
			totalRatingsString: "20+ ratings",
			cloudinaryImageId: "d7746e8be9ff411e4621b7ad4a53936f",
			cuisines: ["Indian", "Biryani", "Snacks"],
			tags: [],
			costForTwo: 20000,
			costForTwoString: "₹200 FOR TWO",
			deliveryTime: 26,
			minDeliveryTime: 26,
			maxDeliveryTime: 26,
			slaString: "26 MINS",
			lastMileTravel: 1.399999976158142,
			slugs: {
				restaurant: "om-sai-hotel-nerul-nerul",
				city: "mumbai",
			},
			cityState: "5",
			address:
				"12C, Sector 1, Shiravane, Nerul, Navi Mumbai, Maharashtra 400706, India",
			locality: "Shiravane",
			parentId: 151748,
			unserviceable: false,
			veg: false,
			select: false,
			favorite: false,
			tradeCampaignHeaders: [],
			chain: [],
			feeDetails: {
				fees: [
					{
						name: "distance",
						fee: 2900,
						message: "",
					},
					{
						name: "time",
						fee: 0,
						message: "",
					},
					{
						name: "special",
						fee: 0,
						message: "",
					},
				],
				totalFees: 2900,
				message: "",
				title: "Delivery Charge",
				amount: "2900",
				icon: "",
			},
			availability: {
				opened: true,
				nextOpenMessage: "",
				nextCloseMessage: "",
			},
			longDistanceEnabled: 0,
			rainMode: "NONE",
			thirdPartyAddress: false,
			thirdPartyVendor: "",
			adTrackingID: "",
			badges: {
				imageBased: [],
				textBased: [],
				textExtendedBadges: [],
			},
			lastMileTravelString: "1.3 kms",
			hasSurge: false,
			aggregatedDiscountInfoV3: {
				header: "40% OFF",
				subHeader: "ABOVE ₹159",
				discountTag: "FLAT DEAL",
				headerTypeV2: 0,
			},
			loyaltyDiscoverPresentationInfo: {
				logoCtx: {
					text: "BENEFITS",
					logo: "v1634558776/swiggy_one/OneLogo_3x.png",
				},
				freedelMessage: "FREE DELIVERY",
				exclusiveOfferMessage: "",
			},
			sla: {
				restaurantId: "645850",
				deliveryTime: 26,
				minDeliveryTime: 26,
				maxDeliveryTime: 26,
				lastMileTravel: 1.399999976158142,
				lastMileDistance: 0,
				serviceability: "SERVICEABLE",
				rainMode: "NONE",
				longDistance: "NOT_LONG_DISTANCE",
				preferentialService: false,
				iconType: "EMPTY",
			},
			promoted: false,
			avgRating: "3.5",
			totalRatings: 20,
			new: false,
		},
		subtype: "basic",
	},
	{
		type: "restaurant",
		data: {
			type: "F",
			id: "87998",
			name: "Gokool Veg Restaurant",
			uuid: "81b7a3f4-1787-4913-861e-139c941fbb16",
			city: "5",
			area: "Sanpada",
			totalRatingsString: "5000+ ratings",
			cloudinaryImageId: "tx7exhbtrag0z3dkkea6",
			cuisines: ["Indian", "Chinese", "South Indian"],
			tags: [],
			costForTwo: 30000,
			costForTwoString: "₹300 FOR TWO",
			deliveryTime: 25,
			minDeliveryTime: 25,
			maxDeliveryTime: 25,
			slaString: "25 MINS",
			lastMileTravel: 1.600000023841858,
			slugs: {
				restaurant: "gokool-veg-restaurant-sanpada-vashi",
				city: "mumbai",
			},
			cityState: "5",
			address:
				"9 To 14, Yashashree Plaza, Sector 8, Sanpada, Navi Mumbai",
			locality: "Sector 8, Sanpada",
			parentId: 88142,
			unserviceable: false,
			veg: true,
			select: false,
			favorite: false,
			tradeCampaignHeaders: [],
			chain: [],
			feeDetails: {
				fees: [
					{
						name: "distance",
						fee: 2900,
						message: "",
					},
					{
						name: "time",
						fee: 0,
						message: "",
					},
					{
						name: "special",
						fee: 0,
						message: "",
					},
				],
				totalFees: 2900,
				message: "",
				title: "Delivery Charge",
				amount: "2900",
				icon: "",
			},
			availability: {
				opened: true,
				nextOpenMessage: "",
				nextCloseMessage: "",
			},
			longDistanceEnabled: 0,
			rainMode: "NONE",
			thirdPartyAddress: false,
			thirdPartyVendor: "",
			adTrackingID: "",
			badges: {
				imageBased: [],
				textBased: [],
				textExtendedBadges: [],
			},
			lastMileTravelString: "1.6 kms",
			hasSurge: false,
			aggregatedDiscountInfoV3: {
				header: "₹75 OFF",
				subHeader: "ABOVE ₹299",
				discountTag: "FLAT DEAL",
				headerTypeV2: 0,
			},
			loyaltyDiscoverPresentationInfo: {
				logoCtx: {
					text: "BENEFITS",
					logo: "v1634558776/swiggy_one/OneLogo_3x.png",
				},
				freedelMessage: "FREE DELIVERY",
				exclusiveOfferMessage: "",
			},
			sla: {
				restaurantId: "87998",
				deliveryTime: 25,
				minDeliveryTime: 25,
				maxDeliveryTime: 25,
				lastMileTravel: 1.600000023841858,
				lastMileDistance: 0,
				serviceability: "SERVICEABLE",
				rainMode: "NONE",
				longDistance: "NOT_LONG_DISTANCE",
				preferentialService: false,
				iconType: "EMPTY",
			},
			promoted: false,
			avgRating: "4.1",
			totalRatings: 5000,
			new: false,
		},
		subtype: "basic",
	},
];
